# Generated by Django 6.0.4 on 2026-04-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVendedor',
            fields=[
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to='backend.vendedor')),
                ('razao_social', models.CharField(blank=True, max_length=150)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20)),
                ('banco', models.CharField(blank=True, max_length=50)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('chave_pix', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'perfis_vendedores',
                'ordering': ['vendedor'],
            },
        ),
    ]
