# Generated by Django 6.0.4 on 2026-04-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criado_em',
            new_name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='backend.vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
