# Generated by Django 6.0.4 on 2026-04-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_criado_em_produto_data_cadastro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
    ]
